server:
  port: 8301

spring:
  cloud:
    nacos:
      config:
        server-addr: 192.168.59.1:8848
        namespace: 7f30555e-c5ba-4988-9442-c3f836c8f72e
        group: dev
      discovery:
        namespace: 7f30555e-c5ba-4988-9442-c3f836c8f72e
  config:
    import:
      - optional:nacos:datebase.yml?group=dev&refreshEnabled=true
      - optional:nacos:aliyunOOS.properties?group=dev&refreshEnabled=true
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
