server:
  port: 8301

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: service-vod
      discovery:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: service-vod
  config:
    import:
      - optional:nacos:vod-database.yml?group=service-vod&refreshEnabled=true
      - optional:nacos:vod-aliyunOOS.properties?group=service-vod&refreshEnabled=true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
