# 服务端口
server:
  port: 8302

# 服务名
spring:
  application:
    name: service-order
  profiles:
    active: dev
    # 返回json的全局时间格式
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: dev
      config:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: dev
  config:
    import:
      - optional:nacos:order-database.yml?group=service-order&refreshEnabled=true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml