server:
  port: 8333

spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.59.1:8848
        namespace: public
        group: dev
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-vod
          uri: http://localhost:8301/
          predicates:
          - Path=/admin/vod/**
