server:
  port: 8304

spring:
  application:
    name: service-user
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: dev
      discovery:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: dev
  config:
    import:
      - optional:nacos:user-database.yml?group=service-user&refreshEnabled=true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
