server:
  port: 8333

spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.59.1:8848
        namespace: 5b1a127f-9baa-4a5f-a709-e0b67cb7ef3d
        group: dev
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # service-vod 模块
        - id: service-vod
          uri: lb://service-vod
          predicates:
          - Path=/admin/vod/**

        # service-order 模块
        - id: service-order
          uri: lb://service-order
          predicates:
          - Path=/admin/order/**

        # service-activity 模块
        - id: service-activity
          uri: lb://service-activity
          predicates:
          - Path=/admin/activity/**

        # service-user 模块
        - id: service-user
          uri: lb://service-user
          predicates:
          - Path=/admin/user/**